# @see https://devdocs.prestashop.com/1.7/modules/concepts/controllers/admin-controllers/#how-to-map-an-action-of-your-controller-to-a-uri
ps_elasticmainmenu_index:
    path: /elastic-mainmenu/index
    methods: [GET]
    defaults:
        _controller: 'Module\ElasticMainmenu\Controller\Admin\ElasticmainmenuController::indexAction'
        _legacy_controller: 'AdminElasticMainmenu'
        _legacy_link: 'AdminElasticMainmenu'
ps_elasticmainmenu_category:
    path: /elastic-mainmenu/category/{id_parent}
    methods: [GET]
    defaults:
        _controller: 'Module\ElasticMainmenu\Controller\Admin\ElasticmainmenuController::categoryAction'
        _legacy_controller: 'AdminElasticMainmenu'
        _legacy_link: 'AdminElasticMainmenu'
ps_elasticmainmenu_updatepositions:
    path: /elastic-mainmenu/updatepositions/{idstart}/{idend}
    methods: [GET]
    defaults:
        _controller: 'Module\ElasticMainmenu\Controller\Admin\AdminTableController::updatePositions'
        _legacy_controller: 'AdminElasticMainmenu'
ps_elasticmainmenu_test:
    path: /elastic-mainmenu/test/{idstart}/{idend}
    methods: [GET]
    defaults:
        _controller: 'Module\ElasticMainmenu\Controller\Admin\AdminTableController::test'
        _legacy_controller: 'AdminElasticMainmenu'