imports:
    - { resource: ./common.yml }

services:
    prestashop.module.elasticmainmenu.controller.admin.elasticmainmenu:
        class: Module\ElasticMainmenu\Controller\Admin\ElasticmainmenuController
        arguments: ['@prestashop.core.hook.dispatcher', '@prestashop.adapter.legacy.context']
        tags:
            - { name: controller.service_arguments }

    prestashop.module.elasticmainmenu.db.install:
        class: Module\ElasticMainmenu\Database\DbInstaller
        arguments:
            - '@doctrine.dbal.default_connection'
            - '%database_prefix%'



    elasticmainmenu.grid.factory.products:
        class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
        public: true
        arguments:
        - '@elasticmainmenu.grid.definition.factory.products'
        - '@elasticmainmenu.grid.data_provider.products'
        - '@prestashop.core.grid.filter.form_factory'
        - '@prestashop.core.hook.dispatcher'
    elasticmainmenu.grid.definition.factory.products:
        class: 'Module\ElasticMainmenu\Grid\Definition\Factory\ProductGridDefinitionFactory'
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
    elasticmainmenu.grid.data_provider.products:
        class: '%prestashop.core.grid.data.factory.doctrine_grid_data_factory%'
        arguments:
        - '@elasticmainmenu.grid.query_builder.product'
        - '@prestashop.core.hook.dispatcher'
        - '@prestashop.core.grid.query.doctrine_query_parser'
        - 'product'
    elasticmainmenu.grid.query_builder.product:
        class: 'Module\ElasticMainmenu\Grid\Query\ProductQueryBuilder'
        parent: 'prestashop.core.grid.abstract_query_builder'
        public: true
        arguments:
        - '@prestashop.core.query.doctrine_search_criteria_applicator'
        - "@=service('prestashop.adapter.legacy.context').getContext().language.id"
        - "@=service('prestashop.adapter.legacy.context').getContext().shop.id"
        - "@=service('prestashop.adapter.legacy.context').getContext().shop.id_shop_group"
        - "@=service('prestashop.adapter.legacy.context').getContext().shop.getGroup().share_stock"
        - '@prestashop.core.grid.query.filter.doctrine_filter_applicator'
        - '@prestashop.adapter.legacy.configuration'