imports:
    - { resource: ./common.yml }

services:
    prestashop.module.elasticmainmenu.controller.admin.elasticmainmenu:
        class: Module\ElasticMainmenu\Controller\Admin\ElasticmainmenuController
        arguments: ['@prestashop.core.hook.dispatcher', '@prestashop.adapter.legacy.context']
        tags:
            - { name: controller.service_arguments }

    prestashop.module.elasticmainmenu.db.install:
        class: Module\ElasticMainmenu\Database\DbInstaller
        arguments:
            - '@doctrine.dbal.default_connection'
            - '%database_prefix%'
    # Grid services
    prestashop.module.elasticmainmenu.grid.definition.factory.categories:
        class: 'Module\ElasticMainmenu\Grid\Definition\Factory\CategoriesGridDefinitionFactory'
        parent: 'prestashop.core.grid.definition.factory.abstract_grid_definition'
    prestashop.module.elasticmainmenu.grid.factory.categories:
        class: 'PrestaShop\PrestaShop\Core\Grid\GridFactory'
        public: true
        arguments:
            - '@prestashop.module.elasticmainmenu.grid.definition.factory.categories'
            - '@prestashop.module.elasticmainmenu.grid.data_provider.categories'
            - '@prestashop.core.grid.filter.form_factory'
            - '@prestashop.core.hook.dispatcher'
    prestashop.module.elasticmainmenu.grid.data_provider.categories:
        class: '%prestashop.core.grid.data.factory.doctrine_grid_data_factory%'
        arguments:
            - '@prestashop.module.elasticmainmenu.grid.query_builder.categories'
            - '@prestashop.core.hook.dispatcher'
            - '@prestashop.core.grid.query.doctrine_query_parser'
            - 'category'
    prestashop.module.elasticmainmenu.grid.query_builder.categories:
        class: 'Module\ElasticMainmenu\Grid\Query\ElasticMainmenuQueryBuilder'
        parent: 'prestashop.core.grid.abstract_query_builder'
        public: true
        arguments:
            - '@prestashop.core.query.doctrine_search_criteria_applicator'
            - "@=service('prestashop.adapter.legacy.context').getContext().language.id"